// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tksh.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FileUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	Chunk    []byte    `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tksh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tksh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_tksh_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploadRequest) GetFileInfo() *FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

func (x *FileUploadRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tksh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tksh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_tksh_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type NewTransferRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tanggal       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=tanggal,proto3" json:"tanggal,omitempty"`
	Transfer      float64                `protobuf:"fixed64,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	BuktiFilepath string                 `protobuf:"bytes,3,opt,name=bukti_filepath,json=buktiFilepath,proto3" json:"bukti_filepath,omitempty"`
	UploadRequest *FileUploadRequest     `protobuf:"bytes,4,opt,name=upload_request,json=uploadRequest,proto3" json:"upload_request,omitempty"`
}

func (x *NewTransferRecord) Reset() {
	*x = NewTransferRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tksh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTransferRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTransferRecord) ProtoMessage() {}

func (x *NewTransferRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tksh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTransferRecord.ProtoReflect.Descriptor instead.
func (*NewTransferRecord) Descriptor() ([]byte, []int) {
	return file_tksh_proto_rawDescGZIP(), []int{2}
}

func (x *NewTransferRecord) GetTanggal() *timestamppb.Timestamp {
	if x != nil {
		return x.Tanggal
	}
	return nil
}

func (x *NewTransferRecord) GetTransfer() float64 {
	if x != nil {
		return x.Transfer
	}
	return 0
}

func (x *NewTransferRecord) GetBuktiFilepath() string {
	if x != nil {
		return x.BuktiFilepath
	}
	return ""
}

func (x *NewTransferRecord) GetUploadRequest() *FileUploadRequest {
	if x != nil {
		return x.UploadRequest
	}
	return nil
}

type UpdateTransferRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Transfer      float64            `protobuf:"fixed64,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	BuktiFilepath string             `protobuf:"bytes,3,opt,name=bukti_filepath,json=buktiFilepath,proto3" json:"bukti_filepath,omitempty"`
	UploadRequest *FileUploadRequest `protobuf:"bytes,4,opt,name=upload_request,json=uploadRequest,proto3" json:"upload_request,omitempty"`
}

func (x *UpdateTransferRecord) Reset() {
	*x = UpdateTransferRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tksh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTransferRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransferRecord) ProtoMessage() {}

func (x *UpdateTransferRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tksh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransferRecord.ProtoReflect.Descriptor instead.
func (*UpdateTransferRecord) Descriptor() ([]byte, []int) {
	return file_tksh_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTransferRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransferRecord) GetTransfer() float64 {
	if x != nil {
		return x.Transfer
	}
	return 0
}

func (x *UpdateTransferRecord) GetBuktiFilepath() string {
	if x != nil {
		return x.BuktiFilepath
	}
	return ""
}

func (x *UpdateTransferRecord) GetUploadRequest() *FileUploadRequest {
	if x != nil {
		return x.UploadRequest
	}
	return nil
}

type TransferRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: badgerholdIndex:"Id"
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" badgerholdIndex:"Id"`
	Tanggal  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=tanggal,proto3" json:"tanggal,omitempty"`
	Transfer float64                `protobuf:"fixed64,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Bukti    []byte                 `protobuf:"bytes,4,opt,name=bukti,proto3" json:"bukti,omitempty"`
}

func (x *TransferRecord) Reset() {
	*x = TransferRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tksh_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRecord) ProtoMessage() {}

func (x *TransferRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tksh_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRecord.ProtoReflect.Descriptor instead.
func (*TransferRecord) Descriptor() ([]byte, []int) {
	return file_tksh_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferRecord) GetTanggal() *timestamppb.Timestamp {
	if x != nil {
		return x.Tanggal
	}
	return nil
}

func (x *TransferRecord) GetTransfer() float64 {
	if x != nil {
		return x.Transfer
	}
	return 0
}

func (x *TransferRecord) GetBukti() []byte {
	if x != nil {
		return x.Bukti
	}
	return nil
}

type ReportAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportItems []*TransferRecord `protobuf:"bytes,1,rep,name=report_items,json=reportItems,proto3" json:"report_items,omitempty"`
}

func (x *ReportAll) Reset() {
	*x = ReportAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tksh_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAll) ProtoMessage() {}

func (x *ReportAll) ProtoReflect() protoreflect.Message {
	mi := &file_tksh_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAll.ProtoReflect.Descriptor instead.
func (*ReportAll) Descriptor() ([]byte, []int) {
	return file_tksh_proto_rawDescGZIP(), []int{5}
}

func (x *ReportAll) GetReportItems() []*TransferRecord {
	if x != nil {
		return x.ReportItems
	}
	return nil
}

type ReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortBy string `protobuf:"bytes,1,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tksh_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tksh_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_tksh_proto_rawDescGZIP(), []int{6}
}

func (x *ReportRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

var File_tksh_proto protoreflect.FileDescriptor

var file_tksh_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x6b, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a,
	0x11, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x22, 0x27, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x11, 0x4e, 0x65,
	0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x34, 0x0a, 0x07, 0x74, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x74, 0x61,
	0x6e, 0x67, 0x67, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x75, 0x6b, 0x74, 0x69, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x75, 0x6b, 0x74, 0x69,
	0x46, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12, 0x39, 0x0a, 0x0e, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x0d, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x75, 0x6b, 0x74,
	0x69, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x62, 0x75, 0x6b, 0x74, 0x69, 0x46, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x39, 0x0a, 0x0e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0d, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a,
	0x07, 0x74, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x74, 0x61, 0x6e, 0x67,
	0x67, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x75, 0x6b, 0x74, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x62, 0x75, 0x6b, 0x74, 0x69, 0x22, 0x3f, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41,
	0x6c, 0x6c, 0x12, 0x32, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x28, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f,
	0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79,
	0x32, 0xa8, 0x01, 0x0a, 0x0b, 0x54, 0x6b, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x34, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12,
	0x12, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x1a, 0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x28, 0x01, 0x12, 0x3a, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a,
	0x0f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x28, 0x01, 0x12, 0x27, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x0e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0a, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x22, 0x5a, 0x20, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x6e, 0x77, 0x69, 0x73,
	0x65, 0x6c, 0x79, 0x32, 0x36, 0x38, 0x2f, 0x74, 0x6b, 0x73, 0x68, 0x2f, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tksh_proto_rawDescOnce sync.Once
	file_tksh_proto_rawDescData = file_tksh_proto_rawDesc
)

func file_tksh_proto_rawDescGZIP() []byte {
	file_tksh_proto_rawDescOnce.Do(func() {
		file_tksh_proto_rawDescData = protoimpl.X.CompressGZIP(file_tksh_proto_rawDescData)
	})
	return file_tksh_proto_rawDescData
}

var file_tksh_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tksh_proto_goTypes = []interface{}{
	(*FileUploadRequest)(nil),     // 0: FileUploadRequest
	(*FileInfo)(nil),              // 1: FileInfo
	(*NewTransferRecord)(nil),     // 2: NewTransferRecord
	(*UpdateTransferRecord)(nil),  // 3: UpdateTransferRecord
	(*TransferRecord)(nil),        // 4: TransferRecord
	(*ReportAll)(nil),             // 5: ReportAll
	(*ReportRequest)(nil),         // 6: ReportRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_tksh_proto_depIdxs = []int32{
	1, // 0: FileUploadRequest.file_info:type_name -> FileInfo
	7, // 1: NewTransferRecord.tanggal:type_name -> google.protobuf.Timestamp
	0, // 2: NewTransferRecord.upload_request:type_name -> FileUploadRequest
	0, // 3: UpdateTransferRecord.upload_request:type_name -> FileUploadRequest
	7, // 4: TransferRecord.tanggal:type_name -> google.protobuf.Timestamp
	4, // 5: ReportAll.report_items:type_name -> TransferRecord
	2, // 6: TkshService.NewTransfer:input_type -> NewTransferRecord
	3, // 7: TkshService.UpdateTransfer:input_type -> UpdateTransferRecord
	6, // 8: TkshService.GetReport:input_type -> ReportRequest
	4, // 9: TkshService.NewTransfer:output_type -> TransferRecord
	4, // 10: TkshService.UpdateTransfer:output_type -> TransferRecord
	5, // 11: TkshService.GetReport:output_type -> ReportAll
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tksh_proto_init() }
func file_tksh_proto_init() {
	if File_tksh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tksh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tksh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tksh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTransferRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tksh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTransferRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tksh_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tksh_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tksh_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tksh_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tksh_proto_goTypes,
		DependencyIndexes: file_tksh_proto_depIdxs,
		MessageInfos:      file_tksh_proto_msgTypes,
	}.Build()
	File_tksh_proto = out.File
	file_tksh_proto_rawDesc = nil
	file_tksh_proto_goTypes = nil
	file_tksh_proto_depIdxs = nil
}
